### ISSUE TITLE
System.OutOfMemoryException: Screen-compatible bitmap cannot be created. 

### ISSUE THREAD

**Issue by joshg253** [joshg253/RegexRenamer#3]
Expand "R:\\Music\\!vgmusic\\" in file tree, type 'gr' -- should select "Gran Turismo series\\", but crashes instead:

```
---------------------------
Unhandled exception (RegexRenamer v1.3.1.0)
---------------------------
Congratulations, you've made RegexRenamer crash! :)

Could you please press Ctrl+C to copy this information and paste it in an email to xiperware@gmail.com
along with what you were doing at the time. This will help the developer to identify and fix the problem.

System.OutOfMemoryException: Screen-compatible bitmap cannot be created. The screen bitmap format cannot be determined.
   at System.Drawing.BufferedGraphicsContext.bFillBitmapInfo(IntPtr hdc, IntPtr hpal, BITMAPINFO_FLAT& pbmi)
   at System.Drawing.BufferedGraphicsContext.CreateCompatibleDIB(IntPtr hdc, IntPtr hpal, Int32 ulWidth, Int32 ulHeight, IntPtr& ppvBits)
   at System.Drawing.BufferedGraphicsContext.CreateBuffer(IntPtr src, Int32 offsetX, Int32 offsetY, Int32 width, Int32 height)
   at System.Drawing.BufferedGraphicsContext.AllocBuffer(Graphics targetGraphics, IntPtr targetDC, Rectangle targetRectangle)
   at System.Drawing.BufferedGraphicsContext.AllocBufferInTempManager(Graphics targetGraphics, IntPtr targetDC, Rectangle targetRectangle)
   at System.Drawing.BufferedGraphicsContext.Allocate(IntPtr targetDC, Rectangle targetRectangle)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---------------------------
OK   
---------------------------
```

And then while copying the dlg:

```
---------------------------
DataGridView Default Error Dialog
---------------------------
The following exception occurred in the DataGridView:

System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at System.Drawing.Icon.ToBitmap()
   at System.Drawing.ImageConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Windows.Forms.Formatter.FormatObjectInternal(Object value, Type targetType, TypeConverter sourceConverter, TypeConverter targetConverter, String formatString, IFormatProvider formatInfo, Object formattedNullValue)
   at System.Windows.Forms.Formatter.FormatObject(Object value, Type targetType, TypeConverter sourceConverter, TypeConverter targetConverter, String formatString, IFormatProvider formatInfo, Object formattedNullValue, Object dataSourceNullValue)
   at System.Windows.Forms.DataGridViewCell.GetFormattedValue(Object value, Int32 rowIndex, DataGridViewCellStyle& cellStyle, TypeConverter valueTypeConverter, TypeConverter formattedValueTypeConverter, DataGridViewDataErrorContexts context)

To replace this default dialog please handle the DataError event.
---------------------------
OK   
---------------------------
```

^ And then the same DataGridView error again while closing that dlg.

Trying the same on GT music dir via "Rename using RegExRenamer" context menu crashes & disappears before I can see anything.

# Sys info:

Windows 11 / 4K display via Ryzen 5700G gfx / 64GB RAM.

**Comment by joshg253** [comment]
P.S. saw that first error before and patched using "4gb\_patch.exe" (used for some games to let them use more memory) -- did not help.

![](https://github.com/joshg253/RegexRenamer/assets/297115/c67690cb-3320-4d8b-b09f-1bb36d515255)
